apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
    namespace: homepage
type: Opaque
stringData:
    HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:JAT9gpXuOSjyeArsqGSEAHJswVwDti1rBAZ0+gJ1Ysc=,iv:piDkYhxvREeQjh274c2z2fil1AKEY9j5Dx8Glf3+dIA=,tag:Lkd1vDCs/TMsVTZtXVBiFg==,type:str]
    HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:+Ly+4xtsHTWvklP9ctkzsJVm6D9NEpUTTQFYF6Kziu8=,iv:D9Hbl/YN1baM76oo+oCqgI8+OqCJfVw3nvM2ZZbv7/E=,tag:U73ziuxuzFwbO3xVytbj+g==,type:str]
    HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:tkgXGhks26QZbjZ0IO3K59Wj1ub/4Y9/aaPXWB5gqHM=,iv:YVhLhHzOz9pi0me6sF9BUba7jPwuGuqIYEkdQrEC92c=,tag:IuEjgNA8/FjiTKza1dZSGQ==,type:str]
    HOMEPAGE_VAR_BAZARR_KEY: ENC[AES256_GCM,data:b1EQa9mxFy5CFK68GBhNfpUH2MBfWli8cPFoJRYsthg=,iv:04RxGPsUm4j4woDVwxvl8l0CkpYi0jwN4Dm0z1VALAc=,tag:Ozc/QW5oVkZH59/1hA8rlw==,type:str]
    HOMEPAGE_VAR_SAB_KEY: ENC[AES256_GCM,data:RRIzMYb4AviSO+I/bg029+Mgua1dCzNxehiztQuLlR0=,iv:LT8XMvpWnFFK1dkFO1sIa4Q16KZfp+qWFNbdPqZ7Qkg=,tag:aN8sAPYom4vIkdeV7fExkA==,type:str]
    HOMEPAGE_VAR_PLEX_KEY: ENC[AES256_GCM,data:+82pIsYvX134XhYBP/TJ1Nv7SFA=,iv:Jx9dNjpkQjH47szv8NXtSzaFrZpKrJFhgXP5TEiku/8=,tag:UhV7dOVkxJGOwFxV+lbkZw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNXdBdHlZNFJMVGo2U3pz
            YU94UE5DMTcwSWk1L2huN2tIZmtmMi8wS1NvCmk3dVdRQWlkUnVLcHhWQXRKYTQv
            SnY4MlVjRHhUTzBKY0t4SzMxaC9uKzQKLS0tIHdyTUlMNC9Pa3lzeFYwUnpFYm1D
            VUVqcmwzWHc5ZERLSEtoNVNPSkdFVTQKm7bq2EpnNgN15JUdheZyR/f1G81CkRRv
            8+cl8xLggvB5GEn6qXo4ZuzUlbDCx9dXWtLGa2jqWPAA6xuWrJ8DQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s6p4fr0zhx3azja49lvfdgxv2093af6xnrq3kjjw22tk5h7rputq7fdsvj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMG04UW9sdlQ5cEtOcGRj
            VXcwTzBzSitJNUNJbGFoMUs5QkV2TWE3aWhrCmFXVHN5ZU1ZaThtaDVCRUtFeXpk
            dm05N0tuUGNxN3hack1PYjl1MFo4bTgKLS0tIE56VDZFSHNzeGY5cEYvaFBFOWFD
            ckt4Ky9QdXdEcG1WcTJWeUU1blRyUGcKRWonK0XQ/6d2Tj175jh4TnqgOMT51t0z
            sjAdhHo8tmkMmxLbW+lhfeNRpxMPZpWsX6iXuWep3PJye+09fjjqyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rj5crn092ny5fatzt05su4z7qthx5n33npuc0jhzed8umwngfdgssds32a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T20:58:29Z"
    mac: ENC[AES256_GCM,data:BG94ctaOKlq2ctilIaTZ/xC2kpQj0meA2lB2YbZ/0dY4yThucTUy0qDZYd+TMOADePFo7zGR8gNZwLRTIqhBDHOV51k7c6Fj7G+Q3oNqIJncY/mJ0T9mbMx2F4uGzQz5T4dGyk3VWMy7VbXRReWdJnuEfQxbYAtvJoqXaKsKDEs=,iv:skWIyR7NgPNH6RhRmrXx5UcUddOgmXhN/XspLE+wpPM=,tag:PxiYzmMLv9f4BURwlMmzew==,type:str]
    version: 3.13.1
