apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
    namespace: pihole
type: Opaque
stringData:
    FTLCONF_webserver_api_password: ENC[AES256_GCM,data:7wguwEIXhhk=,iv:57DrTJjoy4jcc2SRd6smzYlMzA6+VzJA56qRSsI7ODU=,tag:A+AyNSuE/vfr1Kxan01MlA==,type:str]
    PRIMARY: ENC[AES256_GCM,data:OZUF+fE3ZbX9ob8tC6AqRwI7UkpnG5DDrDA5qqk0nPUcxw==,iv:bsrOKi8xkkPyIC5eYQjukPTyP0OZaabALjjA276p4xs=,tag:MTDFT719OFuGeh3rsUFQpA==,type:str]
    REPLICAS: ENC[AES256_GCM,data:DWbZaFLGiTHCQccEmkOnTeZf9bqo3Y0OD4fNetUULAnlcA==,iv:IZ8n/1yPJXT81iGqxY62w+syY1/mWWm7dzdD5jdXyGM=,tag:JvmOcaJyO+/PqapBMsrDtg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWLzc5ZEJsRitnU3UzSENo
            bDlMMnFSQjF1WU94UjNDeEhHdENOblYrMGhBCkV1QU13QlZzQ0dDeUVlMWpaM1Y0
            cmE0MlF1dTdJeVYwWHlDeVNYRGZmTFUKLS0tIDZTeDZOeFRmS2Vhend2dG1wU0lt
            RWQveHFjRWRpMjRLQjFtY2NQYUJOTG8KA7sBxArqe+p5HNOSBBbE7Or2heCvf60v
            ozcggWs0lYl7OnLf6NjzgKnl/4Ui59jPFbxFvsy+bu3BPqiRa3SX8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s6p4fr0zhx3azja49lvfdgxv2093af6xnrq3kjjw22tk5h7rputq7fdsvj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybUtQSlM5c0ZzK1hmY204
            ak1USjFTNm5KZTJtMlFCOFVXODBNNkMwNmowClJLL2NqVXVTTkZKMVlYVUJJOXcx
            dUJqQUVrL0hPSUt2NEFKZlp1bmo1Z1kKLS0tIFYzcUdNd0xxUU5LTVAxTlhOUTJG
            OEhTcS9RbFZuakNPZU0zdjZjZ3RTZXMK9TBvGHFcowmpJkXe10uD62WBYrsz4Wkr
            nAdCoMF7XUsRtYsTNg6v6js4oF8N241TSItliPGOMIlemwWscZcSNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rj5crn092ny5fatzt05su4z7qthx5n33npuc0jhzed8umwngfdgssds32a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-11T18:31:11Z"
    mac: ENC[AES256_GCM,data:JEUIgIAi3vDI9gM0377kLeHCs4G8hu1scn5h6hIBB8W79rgpOUZVYYnPr8OTwYyRH09rif6SfbXBAylSR3RhaEqd7Nkgvf0udn5RTHC7LsBvu6ibP6OZA07LJUMY4U5cgPcy+X4M7+nu311F0m3/8Zwyxi8477b9ZjJnqAoDbmk=,iv:mWV4CP1i3qQH1gLbPH0roFXt46Lfvb59SLepVc2Uz4Q=,tag:HMIctrTGjeO4DWvWQYImSg==,type:str]
    version: 3.13.1
