apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage.yaml
  - prowlarr.yaml
  - sonarr.yaml
  - radarr.yaml
  - bazarr.yaml
  - sabnzbd.yaml
  - flaresolverr.yaml
  - secret-arr-keys.sops.yaml
  - secret-gluetun.sops.yaml
  - unpackerr.yaml
  - qbittorrent.yaml
  - tdarr.yaml
