apiVersion: v1
data:
    RADARR_API_KEY: ENC[AES256_GCM,data:1HJnqIKhuJ7VgQGad/z/Kw0XuiKq+FsXKqFNaIWmSbV78GJiP8UtGBmUUOo=,iv:Y7DIzFI+QqNd1nbHrroHO3/6QVFh5JoA7s5+fBKgurY=,tag:RVqp9AmdLmFaIZ3cLnkFZg==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:scjQtcaHtnPSWExoyzsuBkTjdfr47nN00Ix4Yka5kdA/T5cPzqoEZ4ntns8=,iv:CgBR/HB7cu56UUIEI0Wqmh+n0Syo3Pvf2MV3bCveHxQ=,tag:vC2SNXxrjXb+po99xhySxg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: media-arr-keys
    namespace: media
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENWhzY2FLWUJNNEZNa1ln
            clFFUzdKNHNHKzJJL05FMEdrMTBDNlV0dEVJCmh0V1hLYlVPdWR2VlR5Y3U3R2Jw
            OXN3d2FhdzNSK1YzVmJmczBVRlU0RG8KLS0tIHArLytJYnZnN0dSUTJsVXZUR1R4
            ZURPenhDM05BT3J5MjI2S3RVcTNaNFkKslE3zD2qwQWLGVCGY22nxBuArwn5BZQz
            qScVd9d+5ayiiSvDHqp7ySnfHozFs1r34oYEO6rDQHxepF3L0oxK9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s6p4fr0zhx3azja49lvfdgxv2093af6xnrq3kjjw22tk5h7rputq7fdsvj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1SFNVV0ZaaXgvLzZGU1R4
            bm9BQWFXZDB1VEt2aTJuSUNVTllYRG53bm1NCmh6UWV6Qm5QeE9Pd015VWZoeHpM
            bXNhN3hYa1lGS2xlemZxQTFzRzYrMnMKLS0tIElTUC9QdzltNlFZcUk2YTRoZnha
            YmtZUm1vM1VDNUpXS3Z5Si9UWjJ2aVUKlrCUCpT4nmVb3HyHaD97sl56AMXwYgKK
            YlYmmyIW3pqWoYIywrKYLkXBL+Sj+B16B0Z52j8TB7QMTVIVDYtAwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rj5crn092ny5fatzt05su4z7qthx5n33npuc0jhzed8umwngfdgssds32a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T19:24:42Z"
    mac: ENC[AES256_GCM,data:K4CxQOktGkHUJu7950DBRkBb6VdJFqj2UI/o1iNzN2AbHyf5dLpD6BEtuHSW+hLV6NMkj03eNg9aVIuleDc79bs5uVyqwDMsOH1F2jcF6Qvppq/bBkX5KbPc+SV3IHTtvmHaG3eMM5nXogYKwv6B/OPKLq3G6MuX2tWrLJ9IZaA=,iv:N0+g7UcxgTUyanP+mIQQtlX29mbJPrhjalx3w/V+FLY=,tag:Tm3Ld+lLMLPk5b4d1rFgPA==,type:str]
    version: 3.13.1
