apiVersion: v1
data:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:82aPWIiV6XJ86LmUiRr2VxUpnnHW/hxlkr0UvKzBsdZkpB395vSTerPvyjeKw9Ax4FjnVR8BvoMQMSsG,iv:ZtuXlLMOiyrHPn20AGx9nEDqM7Lt/9RgAFcagKQV8ZQ=,tag:3r6oxMeyRxIbL/N45PTldA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: gluetun-wg
    namespace: media
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNGRNNEt6VVFBQXFnYjlP
            UG1TTlpUa2QxaFBsWHYxMzB5cUFBaTdJK0RvCmRHMzJxYWtQc0JlUHBuT2ttV2Ju
            cjJCRk8xalRuVWJVWHI1RklmU1ppaFkKLS0tIDBLMTNNcFEvNVlQMXZDckhTbmdG
            YnltSWtQaUpzcitrZjZXUzd5cFV6TmMKQm+gAtxdUYzChHBMMvNaQ2l6lIfCOeDY
            oyxAzRPXm4L93GNr5tyZQbIzYqyu0DteASlu+nfL+mSBiBxEYJbm6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s6p4fr0zhx3azja49lvfdgxv2093af6xnrq3kjjw22tk5h7rputq7fdsvj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbEFYSW1zaHRBUXNPdE9u
            cFUyRXdNZk93Y25pdGlXZTZMQ0c3U3o2VEFzCi9lSWVLWm51V2RRVmFGYW9pUmlt
            Z1pGZkJ6UXVkNnpsSzJnQXFmcC9pNVkKLS0tIHQ2d21IYm9KSExNdURBOFplaUdE
            RU44U1ZsSnN4MXNSclZXK0ErUVdaK3MKOZzRm3qAWzfJRzf8YhU6VUgwIaDTDPx1
            ZWt4KZoJcNzl+3VIKaJIys277s5xdUdUeL71hTBUIoHmx8jI7ZG0Hw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rj5crn092ny5fatzt05su4z7qthx5n33npuc0jhzed8umwngfdgssds32a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T19:41:19Z"
    mac: ENC[AES256_GCM,data:kbr9cjPb5Cf5SGsiqJqi2Qo8C2IDe0pYnjdIVsqmhpgfGvTVQgTZVpQ5Uhk7B3OzxxknYSwhfFgnmy0n26Aqta7lZaJePqjgypws6MJ+CsSWeEo26lo1INXl51HyKHqrtfadq/eweLXYg0z0JWZlfwZsLUyRLcn1ID6L1LGwKnA=,iv:IqrhUzvoq5Q9gSZStc10JK8rn9Ut/GrQQuRx+R8tA7Q=,tag:vMEgdHbohVSYtladCX36+g==,type:str]
    version: 3.13.1
