apiVersion: v1
data:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:zgJzAE1LP0AHZFCFQgYP4N2Nxa+O9jBQdqkRQV5yBde/xrqmtrVx4uKABS+L7K+CjWIjtOOSF9IshwHr,iv:IMoEn3UVKW5tpd8Tmf/Zly8JXrsBqLQffwvOlA0XvQc=,tag:dWaB7nWo5SrB7kDignRzLw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: gluetun-wg
    namespace: media
stringData:
    CONTROL_SERVER_APIKEY: ENC[AES256_GCM,data:yKSbE8dbQPWzntCN/8/kgJaG0nczriZ1f+4h5YRCH7EvfNckvVSa4dUEVRZf2rR0,iv:vtagfiHvyWfa95ItYpYCKJiEy4L0Ud/i+O3b3msdL4M=,tag:sqEBXeYoWhi8Q8oFRrgJXQ==,type:str]
    auth-config.toml: ENC[AES256_GCM,data:z0G4mJ6d8Yh4PHexFWFGn5Ti4QpeS3DzONlZbBXoGNhd2tpYnFKBoKGAe4vJdsWP2gjelFNPUB77noYVmIvxrzUcNCBDxdhMwNuXHbrrIK87kKTyKdTHEsFLCf1ve5N9JxACGfwK56bAown/xPWK3AhEAkORUdM4F1k5Au5M0bDeOaJSaux//gpQXufpLIBnjBfSTzACW7L/XYazRV0gFpiPgQvWqnoPBNuHIssHFBovfLfJv408BA00Q0FyTqOLTZVsVZuW64ezwKg7tnWmi3QMMMi00xFDByjIEj45ow/rBrkwnVNwS7NeILpvp8RyJItDEg==,iv:IZuezGyQTZsYZ0IWHhvItDu7phgoK6bnuZLP9Lt8QoE=,tag:2jy2AqN39xHyKtOro0vTTg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVGhDN2JJaURJSW9qNFlk
            MC9JazNYSFE3SGpLVWQ0czdYK2t0dW5jeFRzCnhjdnBadHlQQ2dkeDlMSkJjVDRF
            aDk5SGhaVnNhalFCNkRiK2dUWlkzWWcKLS0tIEt5UkNwMjQxNG9HYWtqU1VLblZU
            bWdJREV5TitiK0RmZTRMVXVXV2dNOWsKkSjYtg1Tvn3nMc8G1ubHLm+H97DXJHZ9
            NnYcNlC1ldTKbb3LzKBaEELJlONZRAoF0Yt5/uyV6wjRxaYYSYbbbQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s6p4fr0zhx3azja49lvfdgxv2093af6xnrq3kjjw22tk5h7rputq7fdsvj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYzJrU0FzK09rV0w0ekFk
            cld4c0VJYlNVSjFOckVDWWYwMm94Ry9oend3ClBTUGQrRjdKMUtQdGFzSlgwbnNh
            bHVVWXQrNVpRM0ZZdlY0ZGV4SlVDb2MKLS0tIHVraGlTdDJaYjZxUW8yYUJYbWt6
            QnYwcEFDdG02R2FZaWZaVExWZUl4SGsKUz323/hYjh/1lTF3WePq6xvtNkGoU9qv
            ugnazEixRY8xscHCGpwQRShqEPWhVNjkn7BsG31JvRDv7g5RaAaexQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rj5crn092ny5fatzt05su4z7qthx5n33npuc0jhzed8umwngfdgssds32a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T04:23:03Z"
    mac: ENC[AES256_GCM,data:T/t5U3LmLN55qVhAyolf0vUVrk6pzt5202lKGJbitg2X2jaOgu3AnB1YYZjcobKAWgPyE970Iy8anJewPYjQUCJcFP2a9GDimP8VHF5HC8KZDMQ+XREpddC9hdVvBqfc6bCgLW7gDWGfo93RvZxF78WoqpQOdID15MyEcFphjrY=,iv:ByWqwue+TNBCXVuV8pytsNJxboAJmwuE4QSXvWi8Du0=,tag:QEofwz11iI9RzLMsi/CTIQ==,type:str]
    version: 3.13.1
