apiVersion: v1
data:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:zgJzAE1LP0AHZFCFQgYP4N2Nxa+O9jBQdqkRQV5yBde/xrqmtrVx4uKABS+L7K+CjWIjtOOSF9IshwHr,iv:IMoEn3UVKW5tpd8Tmf/Zly8JXrsBqLQffwvOlA0XvQc=,tag:dWaB7nWo5SrB7kDignRzLw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: gluetun-wg
    namespace: media
stringData:
    CONTROL_SERVER_APIKEY: ENC[AES256_GCM,data:yKSbE8dbQPWzntCN/8/kgJaG0nczriZ1f+4h5YRCH7EvfNckvVSa4dUEVRZf2rR0,iv:vtagfiHvyWfa95ItYpYCKJiEy4L0Ud/i+O3b3msdL4M=,tag:sqEBXeYoWhi8Q8oFRrgJXQ==,type:str]
    auth-config.toml: ENC[AES256_GCM,data:oIH2J0+3h63CbTISHpJ8UuDoT/6l7j+rdz2LOabAfhgi6oc3qcpr/xGKQ83H16AfXsK46hIXkpWQsNT8Laqgpg1FEottqDkFGRqwM5jgapnxk79y4D8Uqlcjm0XC1+AZK6sHhn3AhE9GFImnVn04H8KDnw/CN3WHYJggsC4SZSMB6eQCz/kxK1wzi14VyMaNBNOD577YtdKoWh6LpQLf+cIBco2IyRBCA+ZVk7b+3MY9vD0ILfgj3wvboOsZqS79JthFXqDNp/A=,iv:+tN95U5TA3eT41AbMhJ6DcFiDGLWTU1YgW+jl2nWLWM=,tag:8spQUMX/zdiGHQWQmBsrIA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVGhDN2JJaURJSW9qNFlk
            MC9JazNYSFE3SGpLVWQ0czdYK2t0dW5jeFRzCnhjdnBadHlQQ2dkeDlMSkJjVDRF
            aDk5SGhaVnNhalFCNkRiK2dUWlkzWWcKLS0tIEt5UkNwMjQxNG9HYWtqU1VLblZU
            bWdJREV5TitiK0RmZTRMVXVXV2dNOWsKkSjYtg1Tvn3nMc8G1ubHLm+H97DXJHZ9
            NnYcNlC1ldTKbb3LzKBaEELJlONZRAoF0Yt5/uyV6wjRxaYYSYbbbQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s6p4fr0zhx3azja49lvfdgxv2093af6xnrq3kjjw22tk5h7rputq7fdsvj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYzJrU0FzK09rV0w0ekFk
            cld4c0VJYlNVSjFOckVDWWYwMm94Ry9oend3ClBTUGQrRjdKMUtQdGFzSlgwbnNh
            bHVVWXQrNVpRM0ZZdlY0ZGV4SlVDb2MKLS0tIHVraGlTdDJaYjZxUW8yYUJYbWt6
            QnYwcEFDdG02R2FZaWZaVExWZUl4SGsKUz323/hYjh/1lTF3WePq6xvtNkGoU9qv
            ugnazEixRY8xscHCGpwQRShqEPWhVNjkn7BsG31JvRDv7g5RaAaexQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rj5crn092ny5fatzt05su4z7qthx5n33npuc0jhzed8umwngfdgssds32a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T00:32:55Z"
    mac: ENC[AES256_GCM,data:KgOxVhfnhdzsoSQxAf99RKk4nwwdT/ckTNs15gHY6Tftmr2fGnRuKSTKTw8CjsEgvdVj4aAnDyRKZL4tkv9z2FY302wgvwGywt+F/1x+cwgOArmCoxI/MteyhDvZ8gEaXdZF67r/+ubXbxWMHd8aLrdJVTjBKwiHwHXy0U81nU0=,iv:sojy/4fG24YDUi76mKt6sYWbKtiFKF3X5NpMtcaVigY=,tag:Wr/So5xlfs46+iL8w2BCGw==,type:str]
    version: 3.13.1
