apiVersion: v1
kind: Secret
metadata:
    name: romm-secret
    namespace: romm
type: Opaque
stringData:
    #ENC[AES256_GCM,data:jPx15MtkvQgkCbI3Zgo3N+XFt4Xdfr3JN/MLPGZ6JzXGVSkqIjEHht4sQQu8C4WpGXeNNMo=,iv:L/McfRcSyTiknBwZJqH1QmQqR/Y/070CrlMGmviBPC0=,tag:UhEFBSy93Al/YyqytFdVnQ==,type:comment]
    DB_PASSWD: ENC[AES256_GCM,data:3tNKCrFcGndM+FxA10gEnMRr4ArtNkLX6/Pux/EOrrHhqGtMWmgNGicpdvYHqXB+k4iFTPT9qrf6KOz8vr3DLw==,iv:ooTbVEVskWjih0bHvS4qwHjmPxgoZ2b7ykhsehXpX2Q=,tag:AokhMAyHLPfCj28xq9JSqg==,type:str]
    MARIADB_PASSWORD: ENC[AES256_GCM,data:N7LdS5EUvRlXLif476nyAUeGZ2ijjDh+woCj/mbWp2f1EgmMuNyOoKDDZtrbpEP4WFTtx9MAUn641ngpmE9rfg==,iv:hkeLwiTvqfBgDmUHkATT8XOJyZTQooQC5COHv+8yObI=,tag:jBBfCeHImB2KKrPdaD5X2g==,type:str]
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:8kGKZETDcxGxy68DJ32RObZDP3qOoeTdaDqYjsBWJxZOWi0rHRZCsdjgxtUwvXi9xEyJeIz6OC85PEjG5KMe9Q==,iv:HHGviO8GP+2HdTc2z/JkOceJWtRrVCQHRRND7hL7vnA=,tag:+t72xWaBGBVMa+zPg4h5BQ==,type:str]
    ROMM_AUTH_SECRET_KEY: ENC[AES256_GCM,data:5Ay53ekRRr4rOV3g6nUJsnjJ8BxGgo/a9DkX3ajBu01weE3BGsBabzEGAqdD8vjjERYHiUtHiitVlx4Cl7Vv0A==,iv:k8+aOb4x9wysdFShzf6pIhMPopT1Nf+KhvPkibLcXHA=,tag:fg/5xc14HNVMgHBKAdxQww==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTajU1MFFPNjJodHAwSXE4
            NU4rWjhjVTlGY3VTYjNtNFJuTmtCamw0aDE4CkFGNmpxMVlkRW95a1FBQ2VNZWla
            bzE2eUVkYlBxeHZGcEY3cnNnYWZmN1kKLS0tIExER2M5ckVwWXNxelZVdmdMTFkr
            SkhYckdUdWQyTG4vdWdjWGY0T0tzbFEKC0AQCcz43kBXY3dCU/+cpUkELOvxW+1/
            1SA3iz4BOFB1+WzzhqIL/ETCPB1F+AONhP1DRLutXSaI+6x0551S2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s6p4fr0zhx3azja49lvfdgxv2093af6xnrq3kjjw22tk5h7rputq7fdsvj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaa0o4d1FjZGdUT2NQSGJs
            dC9Cc3lDSXg3STE4MHh0VmdFVnV2UURybTB3CnBsVHdUUXRmdTZlOUpGMEhJNURY
            Zno5SzJ4OU9aYzN6MDE2N1k3ZStSY1kKLS0tIG56WGtQQ2ljYzlXVWNXL2p0T1dj
            UXkwNWprUGJNVjFiUGZndWFSalErUmcK05sCIeplAuv4pAXMxnTLt5/0Ioshl/ZZ
            OYinZbajk/bykG82VYJJjT/8i/efg4EpYxrpQq0nUiC2dgqe4HmyBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rj5crn092ny5fatzt05su4z7qthx5n33npuc0jhzed8umwngfdgssds32a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T22:25:25Z"
    mac: ENC[AES256_GCM,data:AypvpvbmFbugBtjmxezzjYamFMPpWII7FS8SH5G7Pc4DCfQ0QgtvR5wRHcDKCMq6RROVBbm3GEhDNMT7re8Q6RErNIoJoZHvxEpMlJtJ1HS6VvddwOD18ZufySMjUHAgLkH1hyxt4wN37BeQd8J4Je4WlsQYJoLhwA9NktiPxmI=,iv:20a4V6gWrICMqTBM1bP/ALWxpAw7RCnygtJfALf+oyo=,tag:dV43+JgK6yKfG0z+KJH6lw==,type:str]
    version: 3.13.1
