apiVersion: v1
data:
    SEARXNG_SECRET: ENC[AES256_GCM,data:xQ+xd9glvlBm8k4cbW1xWtMZzTEMYvdaH80lW+XxpQ3TKx6j/sl7pbvzYBJMWnzol4ZtONwwT18cIbzir3LnAnpO3eHOjFrw6Mrage85k/1YB+LN9Sz0cg==,iv:7UR8iHT5M3sWljm9/n84ydECi8ecYkBJFmiGADZXlQA=,tag:UwL0VZ9eSUcN6HjwdNl3LQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: searxng-secret
    namespace: searxng
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRXBlNnZ3UTg5Z0M3R1Qw
            U2FDc1NoZExxMno0TDJ5YW9VMmVFZkpBVXpRClZOZ0FycUtORzErYTUrMDVhRFM4
            RjZESHlCdmozdFQ0VnFQdDdseGNlVDgKLS0tIDh3dS9xK0ltbnFNUmkwaWVjSU1y
            Nm1UVlVtZWpYOUFJb1kzK1hMUThkdGcKjHRIlRvTI4a9TNzxK7s/bN9LmZ+ZfPrO
            qEslJfpw2w+IKSH+CzTt3q8Nczi3QW6dBdYPKsMrz4tkxMXaokl6lw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s6p4fr0zhx3azja49lvfdgxv2093af6xnrq3kjjw22tk5h7rputq7fdsvj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzd0JWZTUwMFllN0pjdTRE
            UHowR2g0SlZOTi9vdHdzRG8rNXVaNEZHL1RFCmg2RHlybWpOTWhOUmUxVWdVZlpx
            RFdsbkRMdURNK3lTUjhzamozMXZQNzgKLS0tIGhjbGRyUTA3M0ttZE41R2FqUHlR
            eDJCUktyYkI4TlNvK2xZblMvY0xJTHMKcawL850MWvyAbZieJ8DO1tCGvNyn8ute
            SElvNv18x6PIiWa+rlWlnG9MhOIDtxkRTraWMkgIWLSRwSjhGqn/Jw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rj5crn092ny5fatzt05su4z7qthx5n33npuc0jhzed8umwngfdgssds32a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T17:09:34Z"
    mac: ENC[AES256_GCM,data:zg5OHlCzhiLBxPMxf2U2zsZgMrMHGSAiP95FEwci/xhrnX8lpTgSlgw0wmEzWOIVGuQfl4k8FYO769DlTxJXn8v9oQtNk2rmNIvTJuDb/sz+nauQsR8SZg52K0gdNkrt2V7xNqbxBSdM6/UKQgHJt+DNbrEia9NtCAr6xiHvaB8=,iv:vD22eC10hDvzMsCSrextfGjMUcVx4fJ3MQ0hQrQ8Q10=,tag:rCB55CBrflHg1Le03vTL0Q==,type:str]
    version: 3.13.1
