# snmp_exporter auth overlay — the Synology SNMPv2c community. Layered on top of
# the image's bundled snmp.yml as a second --config.file. AUTHORED PLAINTEXT;
# encrypt before committing:
#   sops -e -i kubernetes/apps/monitoring/secret-snmp.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: snmp-auth
    namespace: monitoring
stringData:
    auth.yml: ENC[AES256_GCM,data:ca+LhMW0kGeqNuvvSEWsBa40xLAYvefJ1GgMDcqu5OjQNChVI/6BKwjXJBFNgMWPV03nTvnFAJICkS8O,iv:zBNk56wCSbp+ZL4gZUONV/AjgV7OxOQu+zohwZ26vfM=,tag:mgp15N60IrBqSQodCORxOg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNFFES21BVVZNdmxwNHhU
            aUNKLy9kQXRIbm9aNDc5TnRuVllQbTQ1ZjFNCmRQKzhvMXovVkFZR3RlUElIcTY0
            azhoVzNYVWNOcjBnbDFKYUJFN3NFT2sKLS0tIHhrUTMvV3VUS050ZjdJWDZRTWtP
            TWxpdTgzeXY2Tk9xamVyVVIwYVdEaGcKIQ9ke08F6D5pWhluN1MnTDAD9gYLoQxG
            y/wPnmndy81HqcCkFZc8iDc8JgBxyXqbCxkOWptQIWu85FclCh0eZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s6p4fr0zhx3azja49lvfdgxv2093af6xnrq3kjjw22tk5h7rputq7fdsvj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2M09LRnh5eExqSUhpSGFk
            QnZWVGVaeS9SN3ZDTkxrYW5JakY5alNZZzNJClNUNG9Pb05CdEkvWjUyRUV3TzJj
            ejVmaDdrYWlXYlpqVDNZbHJPTi9TTmMKLS0tIHdSYlU2RXFxenlndDhSKzJVenhB
            c1V6VTYvWkdiKzN0UkNIRW0vTnkxR0UKQwl9ROumhBzfSy5621vfuwSFVXWAyAAk
            IdWIrf+7bMjqblv9M9bnkZNDidFG9Rnf8iGgjjS8TvGGPXenwxSqaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rj5crn092ny5fatzt05su4z7qthx5n33npuc0jhzed8umwngfdgssds32a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T22:06:38Z"
    mac: ENC[AES256_GCM,data:Ofrc0nPPWYkcJk61GDsNxm1cu7/glNtDcTBFW6XRdp3IdDRyb0poxa7A7DqFd2hdb22Op2q4Raq2w8k+oWV/Q9d7qve8Q5xlIvyDZ/KKmyHaPuAy+62UvfkX5fi1WIPSSeskfstZ1lvJfJBVLZO3caSyAPBW5tpKHNzjN0Q/I8Y=,iv:n5cpOyDnFkyFX0C39HKGmSPjuP7RYPjj+DsosZFfLbQ=,tag:mcMCGCKgT8C5GC/hAViLKg==,type:str]
    version: 3.13.1
