port=0
interface=eth0
bind-interfaces
dhcp-range=192.168.87.0,proxy,255.255.255.0
enable-tftp
tftp-root=/srv/tftp
dhcp-userclass=set:ipxe,iPXE
pxe-service=tag:#ipxe,X86-64_EFI,"Chainload to iPXE",ipxe.efi
pxe-service=tag:ipxe,X86-64_EFI,"Talos netboot",http://192.168.87.53:8080/ipxe/boot.ipxe
log-facility=-
log-dhcp
log-queries
