apiVersion: v1
data:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:1w9g9VFGHSwvZ6NqE/3CSnOCi4suawr4OsLZxmAygtLH6+ZKQBzx4TmUCh3o8GQhEju/U00iCdnJsTPY6xu6hw==,iv:7AnFmfcHJ1+6MRdyRxCa7ptsH4ZB6gc6YZqjOl7c2Fs=,tag:V8Cyl6LEOAHxK6eR9XWpqg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: n8n-secret
    namespace: n8n
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsa0VNbW5RNVhNcS9hQlMv
            MDRrMkhuYkRwUVhrYzFGczR6NVF2WUFkc3lrCjFjVE4rcXdIeFJvRkZTUHRlckF5
            M1hIbDJIcXAzbWx5R3duQlliL2tJZEEKLS0tIGNBK0dwQ3VkSjNKTU9MeXp0akxy
            Z05MUnovOFZnSzBMODU4R1orRTBzQzgKsILnnUxhGHmcuF8F/mfYOy5OJPWbuF1I
            ghncqnA7YiK4UDhlbykjs6OUYK0oRLOjbXXgwgdWRRmVZk+N+2LJeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s6p4fr0zhx3azja49lvfdgxv2093af6xnrq3kjjw22tk5h7rputq7fdsvj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aGhPSVpTWDlua0diN1p5
            aVFLbnFvZGo1T2o4MEs3TEpyMyt2TVdjeG5vCis0QjBCWTM2V25ZMHVIWEloQjJC
            VjNnNEtKUXMweURwVS9JRXhYSnYrUlEKLS0tIGRlN0JWY2RRMlozOUU5TTd4MmVl
            WXNHS0ZrL3pHR3VjY1BpSmFXUEVVYjQKC7qbKpNF/0b388R9tJCOfQcogT5bBDOG
            c20JvOPuiCzBscgA9RdCdVGUB6c+7DSiuDqVPfZeKRDttiTdSyVdMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rj5crn092ny5fatzt05su4z7qthx5n33npuc0jhzed8umwngfdgssds32a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T17:17:01Z"
    mac: ENC[AES256_GCM,data:j69lIt1wpuoxnH/1VGv6aC6Oe8xKme/kzaywH0Xz21w1z2Tbm4EugNEdOLOmQevTtWSXIqsNVtyQ1miNC1/F/OjVmB+EwuE/hD2jRzV77t1hL9VaVh/9gbd8Kfuyrf51zc7ElofQOScNXBW2gxMPYl3AA3kCvVV+NYMqVoZvnBI=,iv:qYkRSyAyTeWXZ0YAR2WzTWJcco7DzNus8eMZ82HoVa8=,tag:ws69oMg2YsLXrx6Fgf3j/A==,type:str]
    version: 3.13.1
