apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:6Bcd7DkLw6R3vPQFzt6mcPI=,iv:1gNWP+Hao3Ca3jm0GJqhZzNVoVTzNpuXRz+rK3hmg34=,tag:BvE/aWbvxz0EBKGmSgaGCg==,type:str]
    client_secret: ENC[AES256_GCM,data:ndZzCGlqZVVjdcNHn/dlsZ6llnzwgO8x96CDXyH7ZcJfteZcKczVR1488+EuelNLmARtFdzHCkdjMkwnaI4G7w==,iv:19BWA1Fa3ncEQZZ3az9IL9Rl/0zuCmrN9xBvp91Sxco=,tag:L7NY/+Uyh0FdeFyDUK6g0A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeFhleWd1SGpwTldTYTM3
            cXhINk1WSHVOLzQwRlZueFdkNUVLbTdyNTJVCm5kR1hOMS9JaWxkVFpySFAwYXF1
            UmRnOG5xUTNRWWlrcHVHWUZVdlpqYnMKLS0tIDVmUW53MWdrQ1dSckYxNDE2ckQy
            Q2NkcDZFQTVVNG55cjVCZDhyVlh0U3cKOQdWokeLMEt8JPKUevXv6TuZ5c+UptFz
            fvJrccslpgAD1F0zSobZ7YOf3ESL83PNTGu15OQ25U50w6wB5STxGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s6p4fr0zhx3azja49lvfdgxv2093af6xnrq3kjjw22tk5h7rputq7fdsvj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMk5vbEhFZ0Noa3FtWEVW
            M3o4MnVVcEk4UmhGelRvaUUzWGdVenNmc2hZCmVhLzc5dDRlU3lkTTVLRHRUU2tS
            L1hCVUcweml4TGZ6UUliOTE2VFBTYTAKLS0tIFQxQkluY1B5RTFZTzFSUXlpWmtl
            c2xZVDhvcCtiM3dSTERRZ2pXSmFjencKzTVie2DHfNZ9R1WJW/g42fOsTagLKRYI
            Nw1hOE8gtvlOPUhy9GyjQ0gHGUvdVlPaJyYLOagTQuJo4MiC5Sx09A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rj5crn092ny5fatzt05su4z7qthx5n33npuc0jhzed8umwngfdgssds32a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T21:30:45Z"
    mac: ENC[AES256_GCM,data:WmSyD4YqaoKuJIjro3D/4SnELvNJLzpP3VXe4YgeoZzn7baFEDsOlINVI84eNZlqS5MYkuC2Uc6xDAYqQzLNFj4MwpE6sdwZYRgXXiNSqV1phYJWGYxcP/afjdf48lCwQjhQrGknncbPj0eZmfmhmQFahTc79GByK9RqD/zDMYQ=,iv:Iz1PwTMsVq2TUe5Y71kofH1D8s7qqPhCy6VLkketcwY=,tag:GaVm3Pt9h/x2XYT1J02Mxg==,type:str]
    version: 3.13.1
