apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
configMapGenerator:
  - name: wud-aggregator-script
    namespace: wud-aggregator
    files:
      - wud_aggregator.py
generatorOptions:
  disableNameSuffixHash: true
